### PR TITLE
Xgboost sequential

### PR DESCRIPTION
**Pull request by oriashush**
Split Xgboost example to have 2 version - scatter and gather and sequential scatter and gather.
https://rhinohealth.atlassian.net/browse/RH-2598

### CODE REVIEW

**Comment by atonetti-rhinohealth** [comment]
Can we split the folders under xgboost to xgboost-sag and xgboost-seq-sag.  I think we then need separate README's for each project. I think splitting it will make it more obvious to users that there are two different examples there :)

**Comment by oriashush** [comment]
@atonetti-rhinohealth changed. See also the updated README for the seq-sag

**Comment by tal-rhino** [comment]
Thinking out load: Splitting this into two separate examples may not be the best for the intended audience. Sequential SAG is useful for simulating on a single client, which is usually an interim step in a project, I think users would want to see how to take something using SAG (which is the "default" FL training workflow) and make the small changes to use Sequential SAG.

Hmm, or maybe it is actually good, since then we can guide users to diff between the two folders to see the necessary changes. We'd have to be vigilant about keeping the two examples in sync.

But perhaps keep these under a common parent directory to make it clear that they are two variations of the same example?

**Comment by atonetti-rhinohealth** [comment]
@tal-rhino I like the idea of a common parent folder. I think that would be helpful in understanding the main difference is the aggregator otherwise the examples accomplish the same thing

**Comment by oriashush** [comment]
@atonetti-rhinohealth changed

**Review by atonetti-rhinohealth — APPROVED** [review]
LGTM

**Pull request merged**
