### PR TITLE
Add NVFLARE v2.3 MIMIC CXR example with TensorBoard.

### PR DESCRIPTION
**Pull request by tal-rhino**
This is like the v2.2 example, but adds TensorBoard metric logging of both per-client and aggregated metrics, as well as storing multiple model checkpoints.

Also some minor updates to the Dockerfile reflecting our latest best practices.

NOTE FOR REVIEWERS: The GitHub diff won't be very useful for reviewing. It is much more informative to pull the branch locally and diff to the v2.2 example to see the changes.

In my opinion this should replace the other two MIMIC CXR examples; I don't think we need more than one.

### CODE REVIEW

**Review by oriashush — APPROVED** [review]
looks good

**Comment by tal-rhino** [comment]
@atonetti-rhinohealth, please advise whether you'd like to remove the other MIMIC CXR examples and leave just this one, or if you think there's value in having more than just one.

**Comment by tal-rhino** [comment]
Note that `nvflare-docker-run.sh` doesn't currently support NVFLARE v2.3 (or v2.2, though that is found in the experimental repo). I'm working to implement that before merging this.

**Comment by tal-rhino** [comment]
I've updated `nvflare-docker-run.sh` and `drive_admin_api.py` to support NVFLARE v2.2 and v2.3, as well as not crash when model code tries to write TensorBoard logs to `/tb-logs`.

**Comment by tal-rhino** [comment]
I've also updated the miniconda-based Dockerfile, moving it from the NVFLARE v2.0 MIMIC CXR example to the v2.3 example instead. For some reason it no longer works with v2.0, but works as expected with v2.3. This is possibly due to more recent versions of dependencies and NVFLARE having pinned dependency versions.

**Comment by tal-rhino** [comment]
I've tested the updated scripts with all of the MIMIC CXR examples locally.

**Pull request merged**
